variables:
  HOST: "shoya85.starfree.jp"
  USERNAME: "shoya85.starfree.jp"
  PASSWORD: "anua10fweoi32"

before_script:
  - apt update -qy
  - apt install -y lftp

build:
  script:
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rev pub/ ./pub  --ignore-time --parallel=10; mirror -Rev sys/ ./sys  --ignore-time --parallel=10;"
  only:
    - test
