image: centos:7

# variables:
#   HOST: "s1008.xrea.com"
#   USERNAME: "sweetyhotel"
#   PASSWORD: ""

deploy:
  script:
    - yum install -y epel-release
    - yum install -y ncftp --enablerepo=epel
    - echo "put index.php;put -R sys/;cd public_html/;put -R pub/*;quit"|ncftp -u $USERNAME -p $PASSWORD $HOST
  only:
    - master
